# roles/rh-base/vars/Fedora.yml
---
rhbase_systemd_services:
  - systemd-journald.service
  - systemd-tmpfiles-setup-dev.service
  - systemd-tmpfiles-setup.service

rhbase_dependencies:
  - libselinux-python
  - libsemanage-python
  - firewalld
  - python3-firewall

rhbase_package_manager: dnf
rhbase_package_manager_configuration: /etc/dnf/dnf.conf

rhbase_package_manager_automatic_updates: dnf-automatic
rhbase_package_manager_automatic_updates_config: /etc/dnf/automatic.conf
