# roles/rh-base/vars/RedHat.yml
---
rhbase_systemd_services:
  - systemd-journald
  - systemd-tmpfiles-setup-dev
  - systemd-tmpfiles-setup

rhbase_dependencies:
  - libselinux-python
  - libsemanage-python
  - firewalld

rhbase_package_manager: yum
rhbase_package_manager_configuration: /etc/yum.conf

rhbase_package_manager_automatic_updates: yum-cron
rhbase_package_manager_automatic_updates_config: /etc/yum/yum-cron.conf