root_directory: /usr/share/nginx/html

nginx_ports:
  - http
  - https

nginx_default_config: /etc/nginx/nginx.conf
nginx_site_config: /etc/nginx/conf.d/site.conf
nginx_ssl_config: /etc/nginx/ssl.conf
nginx_cert_directory: /etc/pki/tls/certs
nginx_key_directory: /etc/pki/tls/private

certificate: certificate.crt
private_key: private.pem
csr: domain.csr

private_key_type: ECC
private_key_curve: secp256r1

ssl_session_timeout: 1d
ssl_session_cache: shared:SSL:50m
ssl_session_tickets: 'off'

ssl_protocols: TLSv1.2
ssl_ciphers: ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256
ssl_prefer_server_ciphers: 'on'

hsts: Strict-Transport-Security "max-age=31536000; includeSubDomains" always

nginx_exporter_download: "https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.4.2/nginx-prometheus-exporter-0.4.2-linux-amd64.tar.gz"
nginx_exporter_checksum: "sha256:https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.4.2/sha256sums.txt"

nginx_exporter_user: nginx_exporter
nginx_exporter_group: nginx_exporter
nginx_exporter_directory: /opt/nginx_exporter
nginx_exporter_service: nginx_exporter
nginx_exporter_port: 9113/tcp