---
galaxy_info:
  role_name: prometheus
  company: Mesaguy
  author: Mesaguy
  description: Installs and manages Prometheus and Prometheus exporters

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  license: MIT

  min_ansible_version: 2.5.1

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  platforms:
    - name: Alpine
      versions:
        - all
    - name: Amazon
      versions:
        - all
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch
        - buster
    - name: EL
      versions:
        - 6
        - 7
        - 8
    - name: Fedora
      versions:
        - 20
        - 21
        - 22
        - 23
        - 24
        - 25
        - 26
        - 27
        - 28
        - 29
    - name: opensuse
      versions:
        - all
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - artful
        - bionic
        - cuttlefish

  galaxy_tags:
    # Maximum of 20:
    - alertmanager
    - blackbox
    - exporter
    - jmx
    - kafka
    - gluster
    - haproxy
    - memcached
    - monitor
    - monitoring
    - mysqld
    - node
    - prometheus
    - pushgateway
    - snmp
    - statsd

# List your role dependencies here, one per line. Be sure to remove the '[]' above,
# if you add dependencies to this list.
dependencies: []
