# kilo1 DHCP-server
---
rhbase_firewall_allow_services:
  - dhcp
# DNS servers
dhcp_global_domain_name_servers:
  -  172.16.1.70

#lease times
dhcp_global_default_lease_time: 43200 # = 12u
dhcp_global_max_lease_time: 43200

#global domain
dhcp_global_domain_name: green.local # search domain

# PXEboot config
dhcp_global_bootp: allow
dhcp_global_booting: allow
dhcp_global_next_server: 172.16.1.6  # papa1
dhcp_global_filename: "centos/pxelinux.0"

#subnet per VLAN waarin IP's moeten worden uitgedeeld
#VLAN 20, 30 en 50
dhcp_subnets:
    # VLAN 20
  - ip: 172.16.0.0
    netmask: 255.255.255.0
    routers: 172.16.0.254
    pools:
      - range_begin: 172.16.0.1
        range_end: 172.16.0.253

    # VLAN 30
  - ip: 172.16.1.0
    netmask: 255.255.255.192
    routers: 172.16.1.62
    pools:
      - range_begin: 172.16.1.10
        range_end: 172.16.1.61

    # VLAN 50
  - ip: 172.16.1.64
    netmask: 255.255.255.224
    routers: 172.16.1.94
    pools:
      - range_begin: 172.16.1.80
        range_end: 172.16.1.93

# Fixed IP via MAC
dhcp_hosts:
  - name: Alfa1
    mac: '08:00:27:66:5D:01'
    ip: 172.16.1.65
  - name: Bravo1
    mac: '08:00:27:66:5D:02'
    ip: 172.16.1.66
  - name: Charlie1
    mac: '08:00:27:66:5D:03'
    ip: 172.16.1.67
  - name: Delta1
    mac: '08:00:27:66:5D:04'
    ip: 172.16.1.68
  - name: Echo1
    mac: '08:00:27:66:5D:05'
    ip: 172.16.1.69
  - name: Lima1
    mac: '08:00:27:66:5D:06'
    ip: 172.16.1.2
  - name: Mike1
    mac: '08:00:27:66:5D:07'
    ip: 172.16.1.3
  - name: November1
    mac: '08:00:27:66:5D:08'
    ip: 172.16.1.4
  - name: Oscar1
    mac: '08:00:27:66:5D:09'
    ip: 172.16.1.5
  - name: Papa1
    mac: '08:00:27:66:5D:0A'
    ip: 172.16.1.6
