#httpd_server_admin: bert@linuxlab.lan
#httpd_listen: 8080
---

#--firewall-----------------------------#
rhbase_firewall_allow_services:
  - samba
#-------------------------------#

# rhbase_user_groups:
#   - IT_Administratie
#   - Verkoop
#   - Administratie
#   - Ontwikkeling
#   - Directie 

samba_load_homes: true

#--users-----------------------------#
# rhbase_users: 
#   - name: Robert
#     comment: 'Robert'
#     password: 'abc123!'
#     #shell: /sbin/nologin
#     groups: 
#       - IT_Administratie
#       - Verkoop
#       - Administratie
#       - Ontwikkeling
#       - Directie
#   - name: Els
#     comment: 'Els'
#     password: 'cba321!'
#     groups: 
#       - IT_Administratie
#       - Verkoop
#       - Administratie
#       - Ontwikkeling
#       - Directie
#   - name: Thomas
#     comment: 'Thomas'
#     password: 'def123!'
#     groups: 
#       - Directie
#   - name: Noah
#     comment: 'Noah'
#     password: 'fed321!'
#     groups: 
#       - Directie
#   - name: Emma
#     comment: 'Emma'
#     password: 'ghi123!'
#     groups: 
#       - Verkoop
#   - name: Louise
#     comment: 'Louise'
#     password: 'ihg321!'
#     groups: 
#       - Verkoop
#       - Administratie
#   - name: Marie
#     comment: 'Marie'
#     password: 'jkl123!'
#     groups: 
#       - Ontwikkeling
#   - name: Lucas
#     comment: 'Lucas'
#     password: 'ljk321!'
#     groups: 
#       - Ontwikkeling
#       - IT_Administratie
#   - name: Viktor
#     comment: 'Viktor'
#     password: 'mno123!'
#     groups: 
#       - IT_Administratie
#   - name: Sarah
#     comment: 'Sarah'
#     password: 'onm321!'
#     groups: 
#       - IT_Administratie
#       - Verkoop
#   - name: Jade
#     comment: 'jade'
#     password: 'pqr123!'
#     groups: 
#       - Administratie
#   - name: Lars
#     comment: 'Lars'
#     password: 'rqp321!'
#     groups: 
#       - IT_Administratie
#       - Administratie
     


samba_users:
  - name: milan
    password: milan
  - name: bert
    password: bert 
  # - name: Robert
  #   password: abc123!
  # - name: Els
  #   password: cba321!
  # - name: Thomas
  #   password: def123!
  # - name: Noah
  #   password: fed321!
  # - name: Emma
  #   password: ghi123!
  # - name: Louise
  #   password: ihg321!
  # - name: Marie
  #   password: jkl123!
  # - name: Lucas
  #   password: ljk321!
  # - name: Viktor
  #   password: mno123!
  # - name: Sarah
  #   password: onm321!
  # - name: Jade
  #   password: pqr123!
  # - name: Lars
  #   password: rqp321!

samba_shares:
  - name: IT_Administratie
    group: IT_Administratie
    valid_users: +IT_Administratie
    write_list: +IT_Administratie
  - name: Verkoop
    group: Verkoop
    valid_users: +Verkoop
    write_list: +Verkoop
  - name: Administratie
    group: Administratie
    valid_users: +Administratie
    write_list: +Administratie
  - name: Ontwikkeling
    group: Ontwikkeling
    valid_users: +Ontwikkeling
    write_list: +Ontwikkeling
  - name: Directie
    group: Directie
    valid_users: +Directie
    write_list: +Directie



#-------------------------------#

