---
galaxy_info:
  author: Bert Van Vreckem
  description: A role for setting up a Dnsmasq server on CentOS/RHEL 7 or Fedora 16 or newer.
  license: Simplified BSD License
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - 7
    - name: Fedora
      versions:
        - 16
        - 17
        - 18
        - 19
        - 20
        - 21
        - 22
        - 23
  galaxy_tags:
    - networking
    - bind
    - dns
dependencies: []
