---
galaxy_info:
  author: Remco Brink
  description: Configures an LDAP server by creating groups and users
  license: license (BSD, MIT)
  min_ansible_version: 2.0
  platforms:
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  - name: EL
    versions:
    - 6
    - 7
  galaxy_tags:
    - ldap

dependencies: []