---
galaxy_info:
  author: Bert Van Vreckem
  description: >
    Installs the Apache web server on a RedHat based Linux distribution.
  license: BSD
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - 7
    - name: Fedora
      versions:
        - 28
  categories:
    - web
dependencies: []
