---
prometheus_shell: /usr/bin/nologin
prometheus_go_compile_tools:
 - curl
 - gcc
 - git
 - gzip
 - make
prometheus_java_packages:
 - jre8-openjdk-headless
prometheus_prerequisite_packages:
 - tar
 - unzip
prometheus_sponge_packages:
 - moreutils  # For 'sponge'
prometheus_testing_packages:
 - net-tools
 - procps
 - which
