# roles/rh-base/defaults/main.yml
---

# Package management
rhbase_enable_repos: []
rhbase_install_packages: []
rhbase_remove_packages: []
rhbase_repo_exclude: []
rhbase_repo_gpgcheck: false
rhbase_repo_installonly_limit: 3
rhbase_repo_remove_dependencies: true
rhbase_repo_exclude_from_update: []
rhbase_repositories: []
rhbase_update: false

# Configuration
rhbase_override_firewalld_zones: false
rhbase_hosts_entry: false
rhbase_motd: false
rhbase_tz: :/etc/localtime

# Services
rhbase_start_services: []
rhbase_stop_services: []

# Security
rhbase_firewall_allow_services: []
rhbase_firewall_allow_ports: []
rhbase_firewall_interfaces: []
rhbase_selinux_state: enforcing
rhbase_selinux_booleans: []

# Users
rhbase_users: []
rhbase_user_groups: []
