# roles/mailserver/handlers/main.yml
---

- name: restart postfix
  service:
    name: "{{ mailserver_postfix_service }}"
    state: restarted

- name: restart dovecot
  service:
    name: "{{ mailserver_dovecot_service }}"
    state: restarted