---
- name: restart nginx
  service: name=nginx state=restarted
  when: ansible_connection != 'docker'
  
- name: validate nginx configuration
  command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: False
  when: ansible_connection != 'docker'

- name: reload nginx
  service: name=nginx state=reloaded
  when: ansible_connection != 'docker'

- name: daemon-reload
  command: systemctl daemon-reload
  changed_when: false
  when: ansible_connection != 'docker'
