---
dependencies: []
#
galaxy_info:
  author: acandid
  description: Install and Configure MariaDB Galera Cluster 10.3
  company: "Almir Candido"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.7
  platforms:
    - name: EL
      versions:
        - 7
#
  galaxy_tags:
    - database
    - mysql
    - mariadb
    - galera
    - cluster
#
allow_duplicates: true
