---
prometheus_shell: /usr/bin/nologin
prometheus_capabilites_packages:
 - procps-ng
 - which
prometheus_go_compile_tools:
 - curl
 - gcc
 - git
 - gzip
 - make
prometheus_java_packages:
 - java-1.8.0-openjdk-headless
prometheus_prerequisite_packages:
 - tar
 - unzip
prometheus_testing_packages:
 - libselinux-python
 - net-tools
