---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is not defined

- name: Include 389ds_exporter (terrycain) variable file
  include_vars: exporters/389ds_exporter_terrycain.yml

- name: Starting 389ds_exporter (terrycain) install
  set_fact:
    prometheus_exporter: true
    prometheus_software_binary_name: '389ds_exporter'
    prometheus_software_env_vars: '{{ prometheus_389ds_exporter_terrycain_env_vars | default({}) }}'
    prometheus_software_extra_opts: '{{ prometheus_389ds_exporter_terrycain_extra_opts | default() }}'
    prometheus_software_fallback_to_build: '{{ prometheus_389ds_exporter_terrycain_fallback_to_build | default(prometheus_fallback_to_build) }}'
    prometheus_software_makefile_make_command: 'go get -d && go build'
    prometheus_software_name: '389ds_exporter_terrycain'
    prometheus_software_version: '{{ prometheus_389ds_exporter_terrycain_version | default("0.1.2") }}'
    prometheus_software_src_version: '{{ prometheus_389ds_exporter_terrycain_src_version | default("v0.1.2") }}'
    prometheus_software_tgroup_jobname: '{{ prometheus_389ds_exporter_terrycain_jobname | default(prometheus_389ds_exporter_terrycain_default_tgroup_jobname) }}'
    prometheus_software_description: 'Prometheus 389ds_exporter (terrycain), exporter for IPTables metrics'
    prometheus_software_documentation: 'https://github.com/terrycain/389ds_exporter'
    prometheus_software_host: '{{ prometheus_389ds_exporter_terrycain_host | default("0.0.0.0") }}'
    prometheus_software_port: '{{ prometheus_389ds_exporter_terrycain_port | default(prometheus_389ds_exporter_terrycain_default_port) }}'
    prometheus_software_runas: '{{ prometheus_389ds_exporter_terrycain_runas | default(prometheus_user) }}'
    prometheus_software_shortname: '389ds_exporter'

- name: Set {{ prometheus_software_name }}-{{ prometheus_software_version }} facts
  set_fact:
    prometheus_software_opts:
      - '--web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_name_version: '{{ prometheus_software_name }}-{{ prometheus_software_version }}'
    prometheus_software_bin_url: 'https://github.com/terrycain/{{ prometheus_software_shortname }}/releases/download/v{{ prometheus_software_version }}/{{ prometheus_software_shortname }}-{{ prometheus_software_version }}.{{ prometheus_architecture }}.tar.gz'
    prometheus_software_src_dir_suffix: '/src/github.com/terrycain/{{ prometheus_software_shortname }}'
    prometheus_software_src_url: 'https://github.com/terrycain/{{ prometheus_software_shortname }}.git'

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
