---
- name: Install {{ prometheus_software_name_version }} specific prerequisite software
  become: true
  package:
    name: '{{ prometheus_software_dependencies }}'
    state: present
  when: prometheus_software_dependencies is defined and prometheus_software_dependencies|bool

- name: Include task to perform installation of {{ prometheus_software_name_version }} from binary
  include_tasks: _install_from_binary.yml
  when: prometheus_software_bin_url is defined and prometheus_software_bin_url and not prometheus_always_build_from_source|bool

- name: Include task to perform installation of {{ prometheus_software_name_version }} by compiling go source
  include_tasks: _install_from_go_source.yml
  when:
    - prometheus_software_installation is not defined or not prometheus_software_installation or ('failed' in prometheus_software_installation and prometheus_software_installation.failed) or (prometheus_fallback_to_build|bool or prometheus_software_fallback_to_build|bool)
    - prometheus_software_src_url is defined and prometheus_software_src_url

- name: Include task to symlink latest {{ prometheus_software_name_version }} directory to an "active" directory
  include_tasks: _install_active_symlink.yml

- name: Include task to setup capabilites for {{ prometheus_software_name_version }} files
  include_tasks: _setup_capabilities.yml
  loop_control:
    loop_var: prometheus_software_capabilities_file
  with_items: '{{ prometheus_software_capabilities }}'
  when: prometheus_software_capabilities is defined and prometheus_software_capabilities
