---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is not defined

- name: Include bigip_exporter (ExpressenAB) variable file
  include_vars: exporters/bigip_exporter_expressenab.yml

- name: Starting bigip_exporter (ExpressenAB) install
  set_fact:
    prometheus_exporter: true
    prometheus_software_binary_name: 'bigip_exporter'
    prometheus_software_env_vars: '{{ prometheus_bigip_exporter_expressenab_env_vars | default({}) }}'
    prometheus_software_extra_opts: '{{ prometheus_bigip_exporter_expressenab_extra_opts | default() }}'
    prometheus_software_fallback_to_build: '{{ prometheus_bigip_exporter_expressenab_fallback_to_build | default(prometheus_fallback_to_build) }}'
    prometheus_software_name: 'bigip_exporter_expressenab'
    prometheus_software_version: '{{ prometheus_bigip_exporter_expressenab_version | default("1.0.0") }}'
    prometheus_software_src_version: '{{ prometheus_bigip_exporter_expressenab_src_version | default("1.0.0") }}'
    prometheus_software_tgroup_jobname: '{{ prometheus_bigip_exporter_expressenab_jobname | default(prometheus_bigip_exporter_expressenab_default_tgroup_jobname) }}'
    prometheus_software_description: 'Prometheus bigip_exporter (ExpressenAB), exporter for BIG-IP metrics'
    prometheus_software_documentation: 'https://github.com/ExpressenAB/bigip_exporter'
    prometheus_software_host: '{{ prometheus_bigip_exporter_expressenab_host | default("0.0.0.0") }}'
    prometheus_software_port: '{{ prometheus_bigip_exporter_expressenab_port | default(prometheus_bigip_exporter_expressenab_default_port) }}'
    prometheus_software_runas: '{{ prometheus_bigip_exporter_expressenab_runas | default(prometheus_user) }}'
    prometheus_software_shortname: 'bigip_exporter'

- name: Set {{ prometheus_software_name }}-{{ prometheus_software_version }} facts
  set_fact:
    prometheus_software_opts:
      - '--exporter.bind_address={{ prometheus_software_host }}'
      - '--exporter.bind_port={{ prometheus_software_port }}'
    prometheus_software_name_version: '{{ prometheus_software_name }}-{{ prometheus_software_version }}'
    prometheus_software_bin_url: 'https://github.com/ExpressenAB/{{ prometheus_software_shortname }}/releases/download/{{ prometheus_software_version }}/{{ prometheus_software_shortname }}-{{ prometheus_software_version }}.{{ prometheus_architecture }}.tar.gz'
    prometheus_software_src_dir_suffix: '/src/github.com/ExpressenAB/{{ prometheus_software_shortname }}'
    prometheus_software_src_url: 'https://github.com/ExpressenAB/{{ prometheus_software_shortname }}.git'

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
