---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is not defined

- name: Starting jmx_exporter install
  set_fact:
    prometheus_exporter: true
    prometheus_software_binary_name: 'jmx_exporter.jar'
    prometheus_software_config: '{{ prometheus_jmx_exporter_cfgs | default({"default" : ""}) }}'
    prometheus_software_extra_opts: []
    prometheus_software_name: 'jmx_exporter'
    prometheus_software_version: '{{ prometheus_jmx_exporter_version | default("0.12.0") }}'
    prometheus_software_description: 'Prometheus jmx_exporter, JMX to Prometheus exporter'
    prometheus_software_documentation: 'https://github.com/prometheus/jmx_exporter'
    prometheus_software_host: '{{ prometheus_jmx_exporter_host | default("0.0.0.0") }}'
    prometheus_software_port: '{{ prometheus_jmx_exporter_port | default(1234) }}'
    prometheus_software_tgroup_jobname: '{{ prometheus_jmx_exporter_jobname | default("jmx") }}'

- name: Set {{ prometheus_software_name }}-{{ prometheus_software_version }} facts
  set_fact:
    prometheus_software_filename: 'jmx_prometheus_javaagent-{{ prometheus_software_version }}.jar'
    prometheus_software_opts:
      - '--web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_name_version: '{{ prometheus_software_name }}-{{ prometheus_software_version }}'
    prometheus_software_file_url: 'http://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/{{ prometheus_software_version }}/jmx_prometheus_javaagent-{{ prometheus_software_version }}.jar'
    prometheus_software_src_dir_suffix: '/src/github.com/prometheus/{{ prometheus_software_name }}'

- name: Install standalone file for {{ prometheus_software_name_version }}
  include_tasks: _install_file.yml

- name: Setup {{ prometheus_software_name_version }} configuration files
  become: true
  template:
    src: '../templates/jmx-config.yml.j2'
    dest: '{{ prometheus_etc_dir }}/{{ prometheus_software_name }}.{{ jmx_instance.key }}.yml'
    owner: root
    group: root
    mode: '0644'
    backup: true
  loop_control:
    loop_var: jmx_instance
  with_dict: '{{ prometheus_software_config }}'

- name: Include task to perform post install cleanup of {{ prometheus_software_version }}
  include_tasks: _post_install_cleanup.yml
