---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is not defined

- name: Include proxysql_exporter (percona) variable file
  include_vars: exporters/proxysql_exporter_percona.yml

- name: Starting proxysql_exporter (percona) install
  set_fact:
    prometheus_exporter: true
    prometheus_software_binary_name: 'proxysql_exporter'
    prometheus_software_env_vars: '{{ prometheus_proxysql_exporter_percona_env_vars | default({}) }}'
    prometheus_software_extra_opts: '{{ prometheus_proxysql_exporter_percona_extra_opts | default() }}'
    prometheus_software_fallback_to_build: '{{ prometheus_proxysql_exporter_percona_fallback_to_build | default(prometheus_fallback_to_build) }}'
    prometheus_software_makefile_make_command: 'go get -d && go build'
    prometheus_software_name: 'proxysql_exporter_percona'
    prometheus_software_version: '{{ prometheus_proxysql_exporter_percona_version | default("1.1.0") }}'
    prometheus_software_src_version: '{{ prometheus_proxysql_exporter_percona_src_version | default("v1.1.0") }}'
    prometheus_software_tgroup_jobname: '{{ prometheus_proxysql_exporter_percona_jobname | default(prometheus_proxysql_exporter_percona_default_tgroup_jobname) }}'
    prometheus_software_description: 'Prometheus proxysql_exporter (percona), exporter of ProxySQL statistics'
    prometheus_software_documentation: 'https://github.com/percona/proxysql_exporter'
    prometheus_software_host: '{{ prometheus_proxysql_exporter_percona_host | default("0.0.0.0") }}'
    prometheus_software_port: '{{ prometheus_proxysql_exporter_percona_port | default(prometheus_proxysql_exporter_percona_default_port) }}'
    prometheus_software_runas: '{{ prometheus_proxysql_exporter_percona_runas | default(prometheus_user) }}'
    prometheus_software_shortname: 'proxysql_exporter'

- name: Set {{ prometheus_software_name }}-{{ prometheus_software_version }} facts
  set_fact:
    prometheus_software_opts:
      - '--web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_name_version: '{{ prometheus_software_name }}-{{ prometheus_software_version }}'
    prometheus_software_bin_url: 'https://github.com/percona/{{ prometheus_software_shortname }}/releases/download/v{{ prometheus_software_version }}/{{ prometheus_software_shortname }}-{{ prometheus_software_version }}.{{ prometheus_architecture }}.tar.gz'
    prometheus_software_src_dir_suffix: '/src/github.com/percona/{{ prometheus_software_shortname }}'
    prometheus_software_src_url: 'https://github.com/percona/{{ prometheus_software_shortname }}.git'

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
