# roles/rh-base/handlers/main.yml
---

- name: restart journald
  service:
    name: systemd-journald
    state: restarted

- name: restart firewalld
  service:
    name: firewalld
    state: restarted

- name: restart yum-cron
  service:
    name: yum-cron
    state: restarted

- name: restart sshd
  service:
    name: sshd
    state: restarted