# pr001.yml
---

rhbase_firewall_allow_services:
  - dhcp

dhcp_global_domain_name_servers:
  - 172.16.255.254

dhcp_global_default_lease_time: 43200
dhcp_global_max_lease_time: 43200 
dhcp_global_domain_name: green.local

#dhcp_global_classes:
#  - name: vbox
#    match: 'match if binary-to-ascii(16,8,":",substring(hardware, 1, 3)) = "8:0:27"'

dhcp_subnets:
  - ip: 172.16.0.0
    netmask: 255.255.0.0
    routers: 172.16.255.254
    pools:
      - range_begin: 172.16.128.1 
        range_end: 172.16.191.254
        #deny: 'members of "vbox"'
      - range_begin: 172.16.192.1
        range_end: 172.16.192.254
        #allow: 'members of "vbox"'
      - range_begin: 172.16.193.1
        range_end: 172.16.193.254
      - range_begin: 172.16.194.1
        range_end: 172.16.194.254
      - range_begin: 172.16.195.1
        range_end: 172.16.195.254
      - range_begin: 172.16.196.1
        range_end: 172.16.255.254
    

#dhcp_hosts:
#  - name: werkstation
#    mac: '08:00:27:A3:15:A3'  
#   ip: 172.16.128.10